package kegly.organisation.schoolconsoleapp.dao;

import kegly.organisation.schoolconsoleapp.db.ConnectionClass;
import kegly.organisation.schoolconsoleapp.db.DatabaseInitializer;
import kegly.organisation.schoolconsoleapp.entity.Student;
import kegly.organisation.schoolconsoleapp.exception.DaoException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class StudentDaoTest {

    private ConnectionClass connectionClass;
    private StudentDao studentDao;

    @BeforeEach
    void setup() {
        connectionClass = new ConnectionClass("ds-connection.properties");
        studentDao = new StudentDao(connectionClass);

        try (Connection conn = connectionClass.getConnection()) {
            DatabaseInitializer initializer = new DatabaseInitializer("schema.sql");
            initializer.runScript(conn);
        } catch (SQLException e) {
            throw new DaoException(e.getMessage());
        }
    }

    @Test
    void findAll_returnEmptyList_whenDatabaseIsClean() {
        int expectedSize = 0;

        List<Student> result = studentDao.findAll();

        assertEquals(expectedSize, result.size(), "Should return empty list for fresh DB");
    }

    @Test
    void save_shouldAddStudentToDatabase() {
        Student newStudent = new Student(null, "Ivan", "Ivanov");

        studentDao.save(newStudent);

        List<Student> result = studentDao.findAll();

        assertEquals(1, result.size(), "List size should be 1");

        Student savedStudent = result.get(0);
        assertEquals("Ivan", savedStudent.getFirstName());
        assertEquals("Ivanov", savedStudent.getLastName());
        assertNotNull(savedStudent.getStudentId(), "Student ID should be generated by DB");
    }
}